language: php
php:
- 5.4
- 5.5
- 5.6
before_install:
- curl -s http://get.webino.org/support/travis/before-install | sudo sh
install:
- curl -s http://get.webino.org/support/travis/install | sh
before_script:
- curl -s http://get.webino.org/support/travis/before-script | sh
script:
- curl -s http://get.webino.org/support/travis/script | sh
after_success:
- curl -s http://get.webino.org/support/travis/after-success | sh
env:
  global:
    - URI=http://localhost:8000/
    - BROWSER=chrome
    - GH_REF=github.com/webino/WebinoDebug
    - secure: S3N4n+pGEnnwMEOndPa8XRMELfNhj61QS1xdaDg89ZIWzXxixW0HHKkbRuNRIGh8kfjxfUT5zTh3zRyFY9ys9wsfwDA5F4y/r/+NkdkKCEflBpprc9KOo4mtfv/XIp/qHQcRKCL18S3GpDpyEFwNoTqTFgmuUOL6DxJ6yUFFEzo=
